from lib import TODO

from typing import Any


class GoWriter:
    class Node:
        def __init__(self, name: str, *extends: str) -> None:
            self.structs: list[str] = []
            self.extends = extends
            self.name = name

        def add_struct(self, name: str) -> None:
            self.structs.append(name)

        def __str__(self) -> str:
            return self.name

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.interfaces: dict[str, GoWriter.Node] = {}

    def writeln(self, line: str = "") -> None:
        self.lines.append(line)

    def write_interface(self, name: str, *extends: str) -> None:
        self.writeln(f"type {name} interface {"{"}")
        for extend in extends:
            self.writeln(f"\t{extend}")
        self.writeln(f"\t{name}_mark()")
        self.writeln("}")
        self.writeln()
        self.interfaces[name] = GoWriter.Node(name, *extends)

    def _parse_struct(self, info: str) -> tuple[str, str, dict[str, str]]:
        temp: Any
        interface, name, temp = map(lambda x: x.strip(), info.split(":"))
        temp = map(lambda x: x.strip(), temp.split(","))
        temp = map(lambda x: x.split(), temp)
        fields = dict(map(lambda x: (x[0].strip(), x[1].strip()), temp))
        return interface, name, fields

    def write_struct(self, info: str) -> None:
        interface, struct_name, fields = self._parse_struct(info)
        self.writeln(f"type {struct_name}_{interface} struct {"{"}")
        for name, type in fields.items():
            self.writeln(f"\t{name} {type}")
        self.writeln("}")
        self.writeln()
        self.interfaces[interface].add_struct(struct_name)

    def end(self) -> None:
        for interface in self.interfaces.values():
            for struct in interface.structs:
                for extend in interface.extends:
                    self.writeln(
                        f"func (_ *{struct}_{interface}) {extend}_mark() {"{}"}"
                    )
                self.writeln(
                    f"func (_ *{struct}_{interface}) {interface}_mark() {"{}"}"
                )
            self.writeln()

    def write(self, line: str) -> None:
        self.lines[-1] += line

    @property
    def string(self) -> str:
        return "\n".join(self.lines)


PACKAGE = "gen"

NODES = [
    "stmt: expr: expr expr",
    "stmt: for: init stmt, cond expr, post expr, loop stmt",
    "expr: name: name string",
]


def main():
    data = GoWriter()
    data.writeln("/* autogenerated */")
    data.writeln(f"package {PACKAGE}")
    data.writeln()
    data.write_interface("node")
    data.write_interface("stmt", "node")
    data.write_interface("expr", "node")
    for node in NODES:
        data.write_struct(node)
    data.end()

    with open(f"{PACKAGE}.go", "w", encoding="utf-8") as file:
        file.write(data.string)


if __name__ == "__main__":
    raise TODO
    main()
